apiVersion: custom.tekton.dev/v1alpha1
kind: TaskGroup
metadata:
  name: foo
spec:
  params:
  - name: git-url
    type: string
    default: https://github.com/openshift-pipelines/buildkit-tekton
  steps:
  - name: clone
    uses:
      taskRef:
        name: my-git-clone
      parambindings:
      - name: url
        param: git-url
  - name: build
    image: docker.io/library/golang:latest
    script: |
      ls -l /workspace; ls -l /workspace/foo; true
      cd /workspace/foo && go build -v ./...
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: task-group-run-
spec:
  pipelineSpec:
    tasks:
      - name: task-group
        taskRef:
          apiVersion: custom.tekton.dev/v1alpha1
          kind: TaskGroup
          name: foo
        params:
        - name: git-url
          value: https://github.com/openshift-pipelines/go-helloworld-app
