/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	taskgroupv1alpha1 "github.com/openshift-pipelines/tekton-task-group/pkg/apis/taskgroup/v1alpha1"
	versioned "github.com/openshift-pipelines/tekton-task-group/pkg/client/clientset/versioned"
	internalinterfaces "github.com/openshift-pipelines/tekton-task-group/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openshift-pipelines/tekton-task-group/pkg/client/listers/taskgroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TaskGroupInformer provides access to a shared informer and lister for
// TaskGroups.
type TaskGroupInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TaskGroupLister
}

type taskGroupInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTaskGroupInformer constructs a new informer for TaskGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTaskGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTaskGroupInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTaskGroupInformer constructs a new informer for TaskGroup type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTaskGroupInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().TaskGroups(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CustomV1alpha1().TaskGroups(namespace).Watch(context.TODO(), options)
			},
		},
		&taskgroupv1alpha1.TaskGroup{},
		resyncPeriod,
		indexers,
	)
}

func (f *taskGroupInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTaskGroupInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *taskGroupInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&taskgroupv1alpha1.TaskGroup{}, f.defaultInformer)
}

func (f *taskGroupInformer) Lister() v1alpha1.TaskGroupLister {
	return v1alpha1.NewTaskGroupLister(f.Informer().GetIndexer())
}
