/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vdemeester/tekton-task-group/pkg/apis/taskgroup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaskGroups implements TaskGroupInterface
type FakeTaskGroups struct {
	Fake *FakeCustomV1alpha1
	ns   string
}

var taskgroupsResource = schema.GroupVersionResource{Group: "custom.tekton.dev", Version: "v1alpha1", Resource: "taskgroups"}

var taskgroupsKind = schema.GroupVersionKind{Group: "custom.tekton.dev", Version: "v1alpha1", Kind: "TaskGroup"}

// Get takes name of the taskGroup, and returns the corresponding taskGroup object, and an error if there is any.
func (c *FakeTaskGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TaskGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(taskgroupsResource, c.ns, name), &v1alpha1.TaskGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskGroup), err
}

// List takes label and field selectors, and returns the list of TaskGroups that match those selectors.
func (c *FakeTaskGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TaskGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(taskgroupsResource, taskgroupsKind, c.ns, opts), &v1alpha1.TaskGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TaskGroupList{ListMeta: obj.(*v1alpha1.TaskGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.TaskGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taskGroups.
func (c *FakeTaskGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(taskgroupsResource, c.ns, opts))

}

// Create takes the representation of a taskGroup and creates it.  Returns the server's representation of the taskGroup, and an error, if there is any.
func (c *FakeTaskGroups) Create(ctx context.Context, taskGroup *v1alpha1.TaskGroup, opts v1.CreateOptions) (result *v1alpha1.TaskGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(taskgroupsResource, c.ns, taskGroup), &v1alpha1.TaskGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskGroup), err
}

// Update takes the representation of a taskGroup and updates it. Returns the server's representation of the taskGroup, and an error, if there is any.
func (c *FakeTaskGroups) Update(ctx context.Context, taskGroup *v1alpha1.TaskGroup, opts v1.UpdateOptions) (result *v1alpha1.TaskGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(taskgroupsResource, c.ns, taskGroup), &v1alpha1.TaskGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskGroup), err
}

// Delete takes name of the taskGroup and deletes it. Returns an error if one occurs.
func (c *FakeTaskGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(taskgroupsResource, c.ns, name), &v1alpha1.TaskGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaskGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(taskgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TaskGroupList{})
	return err
}

// Patch applies the patch and returns the patched taskGroup.
func (c *FakeTaskGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TaskGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(taskgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TaskGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TaskGroup), err
}
